In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = pd.read_csv('/content/spam.csv',encoding='Windows-1252')

In [ ]:
data.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [ ]:
messages = data[['v1','v2']]
messages.columns = ["label", "text"]

In [ ]:
pd.set_option('display.max_colwidth', None)
messages.head()

label  \
0   ham   
1   ham   
2  spam   
3   ham   
4   ham   

                                                                                                                                                          text  
0                                              Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...  
1                                                                                                                                Ok lar... Joking wif u oni...  
2  Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's  
3                                                                                                            U dun say so early hor... U c already then say...  
4                                                                                                Nah I don't think he goes to usf, he lives around here though

In [ ]:
messages['label']=messages['label'].map({'ham':1,'spam':0})

<ipython-input-7-c6b1a57d9943>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  messages['label']=messages['label'].map({'ham':1,'spam':0})


In [ ]:
messages.head()

label  \
0      1   
1      1   
2      0   
3      1   
4      1   

                                                                                                                                                          text  
0                                              Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...  
1                                                                                                                                Ok lar... Joking wif u oni...  
2  Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's  
3                                                                                                            U dun say so early hor... U c already then say...  
4                                                                                                Nah I don't think he goes to usf, he lives around here though

In [ ]:
messages.shape

(5572, 2)

In [ ]:
from keras.preprocessing import text
tokenizer = text.Tokenizer() 
tokenizer.fit_on_texts(list(messages['text']))
tokenized_texts = tokenizer.texts_to_sequences(messages['text'])

In [ ]:
tokenized_texts[0]

[50,
 469,
 4410,
 841,
 751,
 657,
 64,
 8,
 1324,
 89,
 121,
 349,
 1325,
 147,
 2987,
 1326,
 67,
 58,
 4411,
 144]

In [ ]:
len(tokenized_texts[1])

6

In [ ]:
from keras.utils import pad_sequences
X = pad_sequences(tokenized_texts, maxlen=100)


In [ ]:
X[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,   50,  469, 4410,  841,  751,  657,   64,    8,
       1324,   89,  121,  349, 1325,  147, 2987, 1326,   67,   58, 4411,
        144], dtype=int32)

In [ ]:
tokenizer.word_index

{'i': 1,
 'to': 2,
 'you': 3,
 'a': 4,
 'the': 5,
 'u': 6,
 'and': 7,
 'in': 8,
 'is': 9,
 'me': 10,
 'my': 11,
 'for': 12,
 'your': 13,
 'it': 14,
 'of': 15,
 'call': 16,
 'have': 17,
 'on': 18,
 '2': 19,
 'that': 20,
 'now': 21,
 'are': 22,
 'so': 23,
 'but': 24,
 'not': 25,
 'or': 26,
 'do': 27,
 'can': 28,
 'at': 29,
 "i'm": 30,
 'get': 31,
 'be': 32,
 'will': 33,
 'if': 34,
 'ur': 35,
 'with': 36,
 'just': 37,
 'no': 38,
 'we': 39,
 'this': 40,
 'gt': 41,
 '4': 42,
 'lt': 43,
 'up': 44,
 'when': 45,
 'ok': 46,
 'free': 47,
 'from': 48,
 'how': 49,
 'go': 50,
 'all': 51,
 'out': 52,
 'what': 53,
 'know': 54,
 'like': 55,
 'good': 56,
 'then': 57,
 'got': 58,
 'was': 59,
 'come': 60,
 'its': 61,
 'am': 62,
 'time': 63,
 'only': 64,
 'day': 65,
 'love': 66,
 'there': 67,
 'send': 68,
 'he': 69,
 'want': 70,
 'text': 71,
 'as': 72,
 'txt': 73,
 'one': 74,
 'going': 75,
 'by': 76,
 'home': 77,
 "i'll": 78,
 'need': 79,
 'about': 80,
 'r': 81,
 'lor': 82,
 'sorry': 83,
 'stop': 84,
 'st

In [ ]:
len(tokenizer.word_index)

8920

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, messages['label'].values, test_size=0.2)

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, LSTM, Embedding,SimpleRNN,Dropout

In [ ]:
model = Sequential()

model.add(Embedding(input_dim = len(tokenizer.word_index)+1, output_dim = 128,input_length=100))
model.add(SimpleRNN(10))
model.add(Dropout(0.5))
model.add(Dense(50, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(1, activation='sigmoid'))  

In [ ]:
model.compile(loss='binary_crossentropy', 
              optimizer='adam', 
              metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 100, 128)          1141888   
                                                                 
 simple_rnn_1 (SimpleRNN)    (None, 10)                1390      
                                                                 
 dense_2 (Dense)             (None, 50)                550       
                                                                 
 dropout_1 (Dropout)         (None, 50)                0         
                                                                 
 dense_3 (Dense)             (None, 1)                 51        
                                                                 
Total params: 1,143,879
Trainable params: 1,143,879
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(X_train, y_train, epochs=10, validation_split=0.1)

Epoch 1/10
126/126 [==============================] - 7s 45ms/step - loss: 0.4441 - accuracy: 0.8427 - val_loss: 0.2431 - val_accuracy: 0.8924
Epoch 2/10
126/126 [==============================] - 6s 50ms/step - loss: 0.2051 - accuracy: 0.9334 - val_loss: 0.1056 - val_accuracy: 0.9709
Epoch 3/10
126/126 [==============================] - 5s 42ms/step - loss: 0.0857 - accuracy: 0.9763 - val_loss: 0.0946 - val_accuracy: 0.9619
Epoch 4/10
126/126 [==============================] - 6s 46ms/step - loss: 0.0412 - accuracy: 0.9915 - val_loss: 0.1038 - val_accuracy: 0.9574
Epoch 5/10
126/126 [==============================] - 6s 49ms/step - loss: 0.0223 - accuracy: 0.9950 - val_loss: 0.1021 - val_accuracy: 0.9574
Epoch 6/10
126/126 [==============================] - 5s 42ms/step - loss: 0.0180 - accuracy: 0.9958 - val_loss: 0.1177 - val_accuracy: 0.9574
Epoch 7/10
126/126 [==============================] - 5s 42ms/step - loss: 0.0129 - accuracy: 0.9965 - val_loss: 0.1260 - val_accuracy: 0.9641

In [ ]:
y_pred = model.predict(X_test)

35/35 [==============================] - 0s 9ms/step


In [ ]:
y_pred[0]

array([0.9999337], dtype=float32)

In [ ]:
y_pred[y_pred>0.5] = 1
y_pred[y_pred<=0.5] = 0

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test)

0.9434977578475336

In [ ]:
model = Sequential()

model.add(Embedding(input_dim = len(tokenizer.word_index)+1, output_dim = 128,input_length=100))
model.add(LSTM(10))
model.add(Dropout(0.5))
model.add(Dense(50, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(1, activation='sigmoid'))  

In [ ]:
model.compile(loss='binary_crossentropy', 
              optimizer='adam', 
              metrics=['accuracy'])

In [ ]:
model.fit(X_train, y_train, epochs=10, validation_split=0.1)

Epoch 1/10
126/126 [==============================] - 11s 67ms/step - loss: 0.3335 - accuracy: 0.8836 - val_loss: 0.0929 - val_accuracy: 0.9843
Epoch 2/10
126/126 [==============================] - 8s 65ms/step - loss: 0.0800 - accuracy: 0.9855 - val_loss: 0.0236 - val_accuracy: 0.9955
Epoch 3/10
126/126 [==============================] - 9s 68ms/step - loss: 0.0263 - accuracy: 0.9955 - val_loss: 0.0193 - val_accuracy: 0.9910
Epoch 4/10
126/126 [==============================] - 9s 67ms/step - loss: 0.0116 - accuracy: 0.9988 - val_loss: 0.0122 - val_accuracy: 0.9955
Epoch 5/10
126/126 [==============================] - 8s 63ms/step - loss: 0.0073 - accuracy: 0.9993 - val_loss: 0.0092 - val_accuracy: 0.9955
Epoch 6/10
126/126 [==============================] - 8s 62ms/step - loss: 0.0049 - accuracy: 0.9990 - val_loss: 0.0167 - val_accuracy: 0.9933
Epoch 7/10
126/126 [==============================] - 8s 64ms/step - loss: 0.0029 - accuracy: 0.9998 - val_loss: 0.0253 - val_accuracy: 0.995

In [ ]:
y_pred = model.predict(X_test)
y_pred[y_pred>0.5] = 1
y_pred[y_pred<=0.5] = 0
accuracy_score(y_pred,y_test)

35/35 [==============================] - 1s 12ms/step


0.9829596412556054

In [ ]:
test1 = "Free entry in 2 a wkly comp to win  tkts!!"
test1 = tokenizer.texts_to_sequences([test1])
test2 = pad_sequences(test1, maxlen=100)

In [ ]:
out = model.predict(test2)

1/1 [==============================] - 0s 54ms/step


In [ ]:
out


array([[0.00072082]], dtype=float32)